src/macros.rs
Make sure before we switch to Redis allocator the rest will be out of scope
=> Breaking into scope blocks to make sure all memory allocated before we

examples/data_type.rs, examples/hello.rs, src/macros.rs
The CreateCommand firstkey, lastkey, and keystep defaults aren't working for a module I'm trying to work on. 
I'd really like to make this change non-breaking. But my macro fu is noob-level (at best) and I don't know how to glob all the values after the `$flags:expr` (or even if this is something rust macros support?) and then pass these values as a vec into `redis_command!`. This way we could set defaults instead of passing `1, 1, 1` for most commands.
=> Add Support for CreateCommand Keys

examples/hello.rs, src/context.rs, src/raw.rs, src/redisvalue.rs
- Make a clear distinction between sending a NULL reply and sending no reply at all
- Wrap `RedisModule_IsKeysPositionRequest` and `RedisModule_KeyAtPos`
- Show usage in example
=> Add support for RedisModule_IsKeysPositionRequest

.circleci/config.yml, Cargo.toml, build.sh, src/alloc.rs, src/context.rs, src/lib.rs, src/macros.rs, test.sh
Based on PR #62 and extended to handle the `cfg(test)` limitation.
=> Cleaner way to use redis allocator

Cargo.toml, examples/timer.rs, src/context/mod.rs, src/context/timer.rs
Features:
- Add wrappers for `RedisModule_CreateTimer`, `StopTimer` and `GetTimerInfo`.
- Provide native Rust type-safe handling of user-supplied data and callback.
- Ownership of data is handled using Rust's ownership semantics.
=> Add support for RedisModule_CreateTimer

src/raw.rs
[`RedisModule_SaveStringBuffer`](https://redis.io/topics/modules-api-ref) signature is
```c
void RedisModule_SaveStringBuffer(RedisModuleIO *io, const char *str, size_t len);
```
=> save_string should take `&str` instead of `&String`

examples/data_type.rs, src/macros.rs
- Use `$crate` to avoid hardcoding the module name, which may be
imported by the user under a different name
- Move `use` statements inside function bodies to avoid polluting the
enclosing module's namespace
- Fixes #30
=> Improve macro hygiene by avoiding global `use` (fixes #30)

Cargo.toml, examples/block.rs, examples/threads.rs, src/context/blocked.rs, src/context/mod.rs, src/context/thread_safe.rs, src/lib.rs
The API is similar to `std::sync::Mutex` in that it automatically handles unlocking and freeing, and makes it impossible to use it incorrectly.
For an example, see [examples/threads.rs](examples/threads.rs).
=> Add idiomatic Rust API for ThreadSafeContext

src/redismodule.rs
This makes it more ergonomic to work with `RedisString` objects.
=> Add method for converting RedisString to &str

src/raw.rs
The Rust value "0" was being used as the terminating null pointer signalling the end of the variadic arguments. Unfortunately the type of this expression is i32, which creates a "read-past-the-end" condition in the calling C code. For calls to RedisModule_HashGet with a single argument this seems to usually work correctly, but trying to do the with 2 or more fields crashes with a segmentation fault.
=> Fix usage of RedisModule_HashGet in raw::hash_get

src/rediserror.rs
This obviates the need for the list of conversions from specific error types. Unfortunately
this also requires removing the conversions from `&'static str` and `String`, because future
implementations may cause conflicts.
=> Implement a conversion to RedisError from any type implementing the Error trait

src/rediserror.rs
By convention the first word of the error is an uppercase string indicating the type of error.
=> Make the conversion of Error to RedisError conform to RESP conventions

Cargo.toml, examples/load_unload.rs, src/macros.rs
* Can now run de-init code, similarly to how init code can be specified for a module.
* Added an example module to demonstrate the functionality.
* Also, fixed paths in macros, so that they can compile regardless of which identifiers
the caller has brought into scope.
=> Add support for running module unload code

src/key.rs, src/raw.rs
This commit adds a `hash_get_multi` function in the `raw` module, and a private
`hash_mget_key` function in the `key` module. In the interests of avoiding code
duplication, the corresponding single-get functions are removed, and the public
RedisKey*.hash_get functionality is implemented via multi-get.
Public-facing RedisKey* methods for hash multi-get should be the subject of their
own commit.
=> Add infrastructure for exposing hash-multi-get functionality

Cargo.toml, examples/hello.rs, src/context/mod.rs, src/lib.rs, src/logging.rs, src/raw.rs
- It is sometimes useful to log messages to the Redis logs from code that does not take a context
object. The Redis modules API allows for this by specifying a NULL context, but the Rust wrapper
previously prevented taking advantaged of this ability.
- Added a log_* method for each supported log level to the context object.
- Used `strum` to make translating the LogLevel enum to a string more efficient. This now uses
static strings generated at compile-time, rather than allocating and formatting them dynamically
at runtime on each log call.
=> Add API for context-less logging

src/context/mod.rs, src/lib.rs
These are used in the public ThreadSafeContext API, but were not public. This limits users to using these types implicitly, and prevents them from specifying those types in function signatures.
=> Publicly export `BlockedClient` and `DetachedFromClient`

src/macros.rs
Errant identifier did not properly reference crate context, which made the results dependent on the namespace of the usage environment.
=> Fix reference to Context in `redis_command` macro

src/context/thread_safe.rs
The locking used in it means it is perfectly safe to share references to the same context between threads, similarly to how it's safe to `Send`.
=> Make `ThreadSafeContext` `Sync`

src/context/thread_safe.rs
The `struct` field is apparently never read, causing a compiler warning.
In fact, it's used in the `impl Drop` to call the Redis module API to unblock the client.
=> Fix `unused` compiler warning

examples/data_type.rs, examples/load_unload.rs, src/key.rs, src/redismodule.rs
Generic result type permits obtaining multi-get results in any list- or map-like Rust collection.
=> Add user-facing hash_get_multi functionality to key objects

src/key.rs, src/redismodule.rs
This is both more idiomatic and more flexible than the previous `into_list`/`into_map`. It is now possible to both immediately collect the results into the user's choice of collection, and to perform further manipulations on the results via iterator methods without materializing them into an intermediate collection and incurring allocation costs.
Since the resulting iterator iterates of (key,value) pairs, this comes at the small cost of needing to explicitly `map` the results to collect them into a vector of field-values only.
=> Provide an IntoIterator for the multi-get results

Cargo.toml, build.rs, examples/events.rs, src/lib.rs, src/macros.rs, src/raw.rs
Add optional `event_handlers` field to the `redis_module!` macro that enables
user to specify auto-registered keyspace event handlers.
=> Expose SubscribeToKeyspaceEvents (#77)

src/logging.rs
Fix for #106 where log_notice(), log_verbose() and log_warning() all set log level to LogLevel::Debug.
=> Fix all loglevels mistakenly set to debug

src/context/mod.rs, src/lib.rs
This changes allows 2 things:
1. Allow other modules dev that want to get a raw pointer to the Context, this is helpful for those who use bindgen with the C module to cast between the generator code.
2. Make `key` public to allow importing and using `RedisKey` struct in other higher level structs.
=> Allow access to raw context and RedisKey

.gitignore, examples/load_unload.rs, src/lib.rs, src/macros.rs, src/redismodule.rs
Both the `commands` and `event_handlers` macro callbacks are written in terms of the high-level API. I.e. user gets passed a parameter a "high-level" `Context` (instead of `raw::RedisModuleCtx` pointer), args converted to strings... return values (when necessary) properly handled .etc. `init` and `deinit` appear to be exceptions to this because they require user to write the callbacks in terms of `raw::` types and manually casting statuses to `c_int`... This PR attempts to achieve full consistency by making the init/deinit callback use "high-level" types (though at a cost of a breaking change) so modules will no longer have to mix-and-match "high-level" and "raw" terminology for various callbacks.
* Now a constructed Context reference is passed to init/deinit callbacks
(instead of former …
=> Make init/deinit callbacks use high-level API

src/redismodule.rs
This makes it easier to write tests that naturally provide a `Vec<&str>` instead of a `Vec<String>` which requires manually calling `to_string()` on all items.
The disadvantage of this change is that unlike the previous approach, if we already have an owned `String`, we clone it anyway. 
There doesn't seem to be a way to get both advantages at the same time.
=> Allow the use of NextArg on Iter<&str> as well as Iter<String>

src/key.rs, src/redismodule.rs
A better fix instead of commit 57f10c2 in RedisJSON
"WIP Do not take ownership of RedisModuleString passed to JSONAPI_openKey"
=> WIP open_with_redis_string does not take ownership of the RedisModuleString

src/context/mod.rs, src/raw.rs
The new `export_shared_api` function wraps the underlying `RedisModule_ExportSharedAPI` which is conditionally compiled with `REDISMODULE_EXPERIMENTAL_API`.
Therefore, it should be annotated with `#[cfg(feature = "experimental-api")]` so that code that is built without this feature won't try to compile this function.
=>  Mark export_shared_api with missing experimental-api feature 

Cargo.toml, tests/integration.rs, tests/utils.rs
As discussed in #135, this PR adds infrastructure for integrations tests that can run the example modules inside Redis and perform tests against them.
The infra takes care of starting `redis-server` and shutting it down.
=> Add integration test infrastructure for example modules

src/context/timer.rs
`Context::create_timer()` accepts `data` without static lifetime bounds. This results in runtime errors, if data passed was dropped before callback executes.
Without static bounds on `data`, the following code will panic at runtime(error below code section). But with static bounds, such things will be caught at compile time.
Modified `example/timer.rs`:
```rust
#[macro_use]
extern crate redis_module;
use redis_module::{Context, NextArg, RedisResult};
use std::time::Duration;
fn callback(ctx: &Context, data: String) {
ctx.log_debug(format!("[callback]: {}", data).as_str());
}
type MyData = String;
fn timer_create(ctx: &Context, args: Vec<String>) -> RedisResult {
let mut args = args.into_iter().skip(1);
let duration = args.next_i64()?;
let data: MyData = args.next_string()?;
let timer_id = …
```
=> timer callback data is static

src/redismodule.rs
1. Add `next_str` to NextArg
2. mark all NextArg as `[#inline]`
=> Add next_str to NextArg

.github/workflows/cratesio-publish.yml
Note: This action is valid, but the release itself is untested until release time. It *should* work.
=> automate crate release on release drafter

.circleci/config.yml
To fix the build.
The latest debian release changed the paths on 'stable' and friends, used by redismod. This fixes that.
=> debian change due to their release

examples/hello.rs, src/context/mod.rs, src/lib.rs, src/macros.rs, src/raw.rs, tests/integration.rs
Adding a new argument to `redis_module` macro, which allows specifying a callback function for adding specific module information to the `INFO` command,
e.g., `INFO MODULES`,
or `INFO <module_name>`, for example:
```
127.0.0.1:6379> INFO hello
hello_field:value
127.0.0.1:6379> 
```
(this is in addition to the already used callback function for adding stack trace on panic/crash)
=> Add optional info function to redis_module macro

src/context/mod.rs, src/raw.rs
No need to "assume NULL terminated"
since a `CString` is used and will add the required terminating `NULL`.
=> Remove misleading comments "assume NULL terminated"

examples/hello.rs, src/context/mod.rs, tests/integration.rs
JSON.GET on an existing JSON key with a path containing one or more null characters causes a crash, e.g.,
```
json.set test $ '{}'
OK
json.get test "\x00"
```
=> MOD-2484: avoid crash on null in err reply string

src/error.rs, src/include/redismodule.h, src/key.rs, src/lib.rs, src/raw.rs, src/redismodule.rs
These are useful if you want to save some allocations and manipulate with `RedisString`s directly.
=> `impl {Eq, Ord, Hash} for RedisString`

examples/data_type.rs, src/context/configuration.rs
1. Fixes the warning of the unused result. Now the result is explicitly dropped and so the intention behind the code written is clear.
2. Fixes the typo - "emmutable" to "immutable".
=> Fix minor code issues.

src/redismodule.rs
This will allow to treat RedisString as if it was a `&[u8] `
=> Implement Deref for RedisString that return a &[u8].

Cargo.toml, examples/configuration.rs, examples/events.rs, examples/threads.rs, src/configuration.rs, src/context/info.rs, src/context/keys_cursor.rs, src/context/mod.rs, src/context/thread_safe.rs, src/key.rs, src/lib.rs, src/logging.rs, src/macros.rs, src/raw.rs, src/redismodule.rs, tests/integration.rs
The PR adds the ability to add module configuration as using configuration API introduced on Redis 7: https://github.com/redis/redis/pull/10285
The configuration is added optionally on `redis_module!` macro under `configurations` list that can contains the following subsections:
* `i64` configuration:
A list of `i64` configuration in the following format: `[<name>, <reference to the configuration object>, <default value>, <min value>, <max value>, <flags>, <optional on update callback>]`
* `string` configuration:
A list of `string` configuration in the following format: `[<name>, <reference to the configuration object>, <default value>, <flags>, <optional on update callback>]`
* `bool` configuration:
A list of `bool` configuration in the following format: `[<name>, <reference to the …
=> Added configuration API.

Cargo.toml, examples/call.rs, examples/response.rs, examples/string.rs, src/context/call_reply.rs, src/context/mod.rs, src/include/redismodule.h, src/key.rs, src/lib.rs, src/logging.rs, src/raw.rs, src/rediserror.rs, src/redismodule.rs, src/redisvalue.rs, tests/integration.rs
The PR adds Resp3 support for both, return result from module command and getting result as resp3 on `ctx.call_ext` (when resp3 option is used).
Tests was added to verify both new functionalities.
The PR also refactor the `CallReply` API introduced on https://github.com/RedisLabsModules/redismodule-rs/pull/290. Instead of having 2 types of `CallReply` we now have one type such that the root call reply created with `'static` lifetime indicating that the user can hold it for as long as it want. Internal `CallReply` can outlive its father.
As part of the refactoring, the `CallReply` was changed to be more rust friendly. `CallReply` was renamed to `CallResult = Result<CallReply, ErrorCallReply>`, `CallReply` is an enum which allows to check the `CallReply` type using a `match` statement.
=> add RESP3 new APIs

src/context/call_reply.rs, src/context/mod.rs, src/raw.rs, src/redisvalue.rs
Current behaviour is to append to format to the data. This is wrong because the format need to pass separately to Redis. Also, a wrong RedisModuleAPI was used, we need to use the API that allows to pass the format (otherwise Redis uses the default `txt` format).
=> Fix string verbatim reply to work correctly.

.github/workflows/cratesio-publish.yml
toml-editor can only set strings value. This is good enough for us because we do not really need the `path` argument.
=> Fix publish CI

redismodule-rs-macros-internals/Cargo.toml, redismodule-rs-macros-internals/src/lib.rs
Added `extra-traits` feature to `syn` dependency so we will get the Debug trait implementation.
=> Fix publish CI.

examples/response.rs, src/context/mod.rs, src/redisvalue.rs
The main problem with `HashMap` and `HashSet` is that those are unordered. So we get results in different order each time.
Using `BTreeMap` and `BTreeSet` we will get the results in the same order each time.
=> Use `BTreeMap` and `BTreeSet` in addition to `HashMap` and `HashSet`.

examples/proc_macro_commands.rs, redismodule-rs-macros/src/command.rs, redismodule-rs-macros/src/lib.rs, redismodule-rs-macros/src/redis_value.rs, src/macros.rs, src/redisvalue.rs, tests/integration.rs
`RedisValue` derive proc macro allows to automatically generate the `From` trait of a given struct and convert it to `RedisValue`.
Example:
```rust
#[derive(RedisValue)]
struct RedisValueDeriveInner {
i: i64,
}
#[derive(RedisValue)]
struct RedisValueDerive {
i: i64,
f: f64,
s: String,
u: usize,
v: Vec<i64>,
v2: Vec<RedisValueDeriveInner>,
hash_map: HashMap<String, String>,
hash_set: HashSet<String>,
ordered_map: BTreeMap<String, RedisValueDeriveInner>,
ordered_set: BTreeSet<String>,
}
#[command(
{
flags: [ReadOnly, NoMandatoryKeys],
arity: -1,
key_spec: [
{
notes: "test redis value derive macro",
flags: [ReadOnly, Access],
begin_search: Index({ index : 0 }),
find_keys: Range({ last_key : 0, steps : 0, limit : 0 }),
}
]
}
)]
fn redis_value_derive(_ctx: &Context, _args: Vec<RedisString>) -> …
```
=> Implements `RedisValue` derive proc macro.

examples/proc_macro_commands.rs, redismodule-rs-macros/src/lib.rs, redismodule-rs-macros/src/redis_value.rs, tests/integration.rs
The PR extend the `RedisValue` derive macro with 2 new capabilities:
1. It is possible to use it on an Enum. In this case, the generated code will check the enum varient (using a match statement) and perform `Into` on the matched varient. This is usefull in case the command returns more than a single reply type and the reply type need to be decided at runtime.
2. It is possible to specify field attribute. that will define a specific behavior about the field. Supported attributes:
* flatten - indicate to inlines keys from a field into the parent struct. Example: 
```rust
#[derive(RedisValue)]
struct RedisValueDeriveInner { 
i2: i64, 
}
#[derive(RedisValue)]
struct RedisValueDerive { 
i1: i64,
#[RedisValueAttr{flatten: true}]
inner: RedisValueDeriveInner 
}
```
=> Extend `RedisValue` derive macro.

examples/call.rs, src/context/mod.rs, src/context/thread_safe.rs, src/lib.rs, tests/integration.rs
Sometimes we need to perform operation on Redis from a background thread, for this we need to lock Redis. We can use `ThreadSafeContext` but we might prefer not to for the following reasons:
1. Creating a `ThreadSafeContext` is costly.
2. `ThreadSafeContext` which is not attached to a client do not have the module pointer and this could cause some operations to fail.
The PR adds the ability to lock Redis using the global detached context. After locking, we will get `DetachedContextGuard` object which will automatically unlock Redis when dispose. `DetachedContextGuard` implements `Deref<Context>` so it can be used just like a regular `Context` to perform operations.
**Notice: This context should not be use to return any replies!!!**
**Notice: Locking Redis by a thread that already owns the …
=> Allow lock Redis from global detached context.

src/raw.rs
Starting with rustc 1.70.0, the code in raw.rs:hash_get_multi produced the following warnings:
this `CString` is deallocated at the end of the statement, bind it to a
variable to extend its lifetime
While it would work in practice due to the underlying implementation just doing pointer juggling, this warning was correct: The CString created within the macro `f` would be destroyed before the reference to the pointer taken from it with `as_ptr` was used.
Resolved by allocating a new Vec that contains the CStrings. This ensures they remain alive until the function returns.
=> Fix lifetime warning in Rust 1.70

src/context/mod.rs
`avoid_replication_traffic` will return true iff Redis expect the module to avoid adding commands to the replication stream. This usually happened during fail-overs where we wait for the primary and the replica to be in sync, if the module will continue generating traffic this might never happened.
The API is available sense Redis 6.0, so no need to add it to the `API_VERSION_MAPPING` (default is 6.0).
=> Added avoid_replication_traffic API

src/context/mod.rs
Post notification job callback is kept by Redis for unknown time and so we must force it live for the static lifetime. Notice that this does not mean that the value must live forever, it just means that it can not hold any none static references. For more information: https://practice.rs/lifetime/static.html#t-static
=> Force post notification job callback to static lifetime

.circleci/config.yml, .gitignore, Cargo.toml, build.sh, examples/open_key_with_flags.rs, src/context/mod.rs, src/key.rs, src/raw.rs, test.sh, tests/integration.rs, tests/utils.rs
This PR adds the ability to open key for read or write with additional flags
It adds the function `open_with_flags` both for `RedisKeyWritable` and `RedisKey` as well as the following flags:
```
/// Avoid touching the LRU/LFU of the key when opened.
NOTOUCH,
/// Don't trigger keyspace event on key misses.
NONOTIFY,
/// Don't update keyspace hits/misses counters
NOSTATS,
/// Avoid deleting lazy expired keys.
NOEXPIRE,
/// Avoid any effects from fetching the key.
NOEFFECTS
```
=> open key flags

.circleci/config.yml, redismodule-rs-macros/src/command.rs, redismodule-rs-macros/src/lib.rs, src/context/commands.rs, src/context/mod.rs
The new flag is an enterprise only flag. The new flag will make sure the command will not appeared on slow log, `command` command, and other location where we do not want to expose it.
=> Added support for _proxy-filtered flag.

src/context/mod.rs
The return value of the info reply is a SimpleString, we should support this variant as well.
=> Fix is_enterprise function

src/raw.rs
Add `module_option_handle_repl_async_load` flag to module options
=> Enable diskless replication by supporting async load

src/key.rs
Currently, the `is_empty()` function used to detect if a key is present or not, is way after the Rust documentation for it. This led to the public documentation page to mark that on the wrong API method, which can be misleading. See https://docs.rs/redis-module/latest/redis_module/key/struct.RedisKeyWritable.html
=> Move is_empty() in RedisKeyWritable to its rightful place with the documentation.

Cargo.toml, examples/expire.rs, src/key.rs, tests/integration.rs
Currently `RedisKeyWritable` has no easy way to remove expiration/TTL from a key that already exists in Redis because `set_expire()` takes `Duration` as input even though the underlying `raw::set_expire()` method supports this functionality. 
This PR adds a new method `remove_expire()` to `RedisKeyWritable`.
=> Add API to remove expiration for RedisKeyWritable

examples/data_type.rs, examples/open_key_with_flags.rs, redismodule-rs-macros/src/lib.rs, src/context/commands.rs, src/context/defrag.rs, src/context/mod.rs, src/include/redismodule.h, src/lib.rs, src/macros.rs, tests/integration.rs
The PR adds support for defrag API.
The PR introduce a new struct, `DefragContext`, which provide a safe API over `*mut raw::RedisModuleDefragCtx`.
**Notice** that we do expose an unsafe API to create `DefragContext` from `*mut raw::RedisModuleDefragCtx`. This is because we do not have a safe API for datatype registration. User must register an unsafe function as the defrag callback of the datatype and create the `DefragContext` from `*mut raw::RedisModuleDefragCtx`. We should consider adding a safe API for datatype creation.
In addition, the PR introduce 3 new proc macros:
* defrag_function - allows to register a function to defrag global data
* defrag_start_function - allows to register a function to defrag global data when defrag cycle starts.
* defrag_end_function - allows to register …
=> Added support for defrag API.

examples/acl.rs, src/context/mod.rs, src/include/redismodule.h, src/lib.rs, src/macros.rs, test.sh, tests/integration.rs
- Fixes the problem of naming the meta-variable class `$acl_category` identically to its identifier.
- ~Reduces code duplication on the module side (eg `RedisJSON`), all commands from the module are given the ACL category of the module without having to be expressly listed per command.~
(This is not guaranteed to be correct behavior for all modules. removed).
- Adds a test on the `redismodule-rs` side to ensure it works as expected.
- Allows for a combination of optional ACL categories and mandatory ACL categories to allow for the case of optionally adding categories to commands depending on the state of the Redis Server being accessed (ie v7.2 will fail to add a new ACL category, and therefore any commands that should be linked to that category should be optional). Failing to add …
=> MOD-8036 Add tests for 393 and 394

src/include/redismodule.h
Added the new API, `RedisModule_GetInternalSecret`,  introduce on https://github.com/redis/redis/pull/13740 to `redismodule.h`.
=> Added RM_GetInternalSecret to redismodule.h

Cargo.toml
When building `redis-module`, on Alpine 3, a linker error occurs when trying to dynamically link libclang, a dependency of bindgen:
```
[...] Dynamic loading not supported
```
This can be worked around by statically linking to libclang. This PR allows users of this crate to enable static linking.
=> Add feature flags allowing for statically linking to libclang

.github/workflows/ci.yml, Cargo.toml
Use `bindgen/runtime` feature which is one of the two exclusive bindgen features in cargo.toml
Ensure that features that are `xor` are not used together in the github workflows.
=> Fix CI runs: Use one of the two exclusive bindgen features in CI

tests/integration.rs, tests/utils.rs
Prior:
The integration tests were flaky. They failed for non-obvious reasons, which were related to side effects.
Changes:
- We removed the manual assigned port numbers in two integration tests. That ensures that each integration Test uses it's own Redis Server instance
- We used a separate output directory and filename for the rdb file that may get stored during integration testing.
Result:
The CI in the stacked PR - https://github.com/RedisLabsModules/redismodule-rs/pull/419 - has been completed successfully.
=> MOD-11364: Improves the robustness of integration tests
